// Code generated by goctl. DO NOT EDIT!
// Source: login.proto

package server

import (
	"context"

	"shop-demo/apps/login/rpc/login/internal/logic"
	"shop-demo/apps/login/rpc/login/internal/svc"
	"shop-demo/apps/login/rpc/login/login"
)

type LoginServer struct {
	svcCtx *svc.ServiceContext
	login.UnimplementedLoginServer
}

func NewLoginServer(svcCtx *svc.ServiceContext) *LoginServer {
	return &LoginServer{
		svcCtx: svcCtx,
	}
}

func (s *LoginServer) DoLogin(ctx context.Context, in *login.LoginRequest) (*login.LoginResponse, error) {
	l := logic.NewDoLoginLogic(ctx, s.svcCtx)
	return l.DoLogin(in)
}

func (s *LoginServer) LoginOut(ctx context.Context, in *login.LoginRequest) (*login.LoginRequest, error) {
	l := logic.NewLoginOutLogic(ctx, s.svcCtx)
	return l.LoginOut(in)
}
