// Code generated by goctl. DO NOT EDIT!
// Source: search.proto

package search

import (
	"context"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Search interface {
		SearchKey(ctx context.Context, in *ProductSearchRequest, opts ...grpc.CallOption) (*ProductSearchResponse, error)
	}

	defaultSearch struct {
		cli zrpc.Client
	}
)

func NewSearch(cli zrpc.Client) Search {
	return &defaultSearch{
		cli: cli,
	}
}

func (m *defaultSearch) SearchKey(ctx context.Context, in *ProductSearchRequest, opts ...grpc.CallOption) (*ProductSearchResponse, error) {
	client := NewSearchClient(m.cli.Conn())
	return client.SearchKey(ctx, in, opts...)
}
