// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: seckill.proto

package seckill

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SecKillClient is the client API for SecKill service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SecKillClient interface {
	CreateSecKill(ctx context.Context, in *SecKillRequest, opts ...grpc.CallOption) (*SecKillResponse, error)
}

type secKillClient struct {
	cc grpc.ClientConnInterface
}

func NewSecKillClient(cc grpc.ClientConnInterface) SecKillClient {
	return &secKillClient{cc}
}

func (c *secKillClient) CreateSecKill(ctx context.Context, in *SecKillRequest, opts ...grpc.CallOption) (*SecKillResponse, error) {
	out := new(SecKillResponse)
	err := c.cc.Invoke(ctx, "/seckill.SecKill/CreateSecKill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecKillServer is the server API for SecKill service.
// All implementations must embed UnimplementedSecKillServer
// for forward compatibility
type SecKillServer interface {
	CreateSecKill(context.Context, *SecKillRequest) (*SecKillResponse, error)
	mustEmbedUnimplementedSecKillServer()
}

// UnimplementedSecKillServer must be embedded to have forward compatible implementations.
type UnimplementedSecKillServer struct {
}

func (UnimplementedSecKillServer) CreateSecKill(context.Context, *SecKillRequest) (*SecKillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSecKill not implemented")
}
func (UnimplementedSecKillServer) mustEmbedUnimplementedSecKillServer() {}

// UnsafeSecKillServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecKillServer will
// result in compilation errors.
type UnsafeSecKillServer interface {
	mustEmbedUnimplementedSecKillServer()
}

func RegisterSecKillServer(s grpc.ServiceRegistrar, srv SecKillServer) {
	s.RegisterService(&SecKill_ServiceDesc, srv)
}

func _SecKill_CreateSecKill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecKillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecKillServer).CreateSecKill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seckill.SecKill/CreateSecKill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecKillServer).CreateSecKill(ctx, req.(*SecKillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SecKill_ServiceDesc is the grpc.ServiceDesc for SecKill service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecKill_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seckill.SecKill",
	HandlerType: (*SecKillServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSecKill",
			Handler:    _SecKill_CreateSecKill_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "seckill.proto",
}
