// Code generated by goctl. DO NOT EDIT!
// Source: search.proto

package server

import (
	"context"

	"shop-demo/apps/search/rpc/internal/logic"
	"shop-demo/apps/search/rpc/internal/svc"
	"shop-demo/apps/search/rpc/search"
)

type SearchServer struct {
	svcCtx *svc.ServiceContext
	search.UnimplementedSearchServer
}

func NewSearchServer(svcCtx *svc.ServiceContext) *SearchServer {
	return &SearchServer{
		svcCtx: svcCtx,
	}
}

func (s *SearchServer) SearchKey(ctx context.Context, in *search.ProductSearchRequest) (*search.ProductSearchResponse, error) {
	l := logic.NewSearchKeyLogic(ctx, s.svcCtx)
	return l.SearchKey(in)
}
